server:
  port: 8081

spring:
  application:
    name: hmdp
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://124.222.35.20:3319/hmdp?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
    username: ding
    password: dyw20020304
  redis:
    host: 124.222.35.20
    port: 6666
    password: dyw20020304
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
  main:
    allow-circular-references: true # 允许循环依赖
mybatis-plus:
  type-aliases-package: top.devildyw.hmdp.entity # 别名扫描包
logging:
  level:
    top.devildyw.hmdp: debug
